# Generated by Django 4.1.13 on 2024-08-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_coffee_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
